Mark unused parameters by casting to void
This is the way unused parameters are dealt with in the rest of the
tinyusb codebase. It prevents the following warning when building
with -Wextra:

```C
In file included from [redacted]/pico-sdk/lib/tinyusb/src/osal/osal.h:57,
                 from [redacted]/pico-sdk/lib/tinyusb/src/tusb.h:38,
                 from [redacted]/pico-sdk/lib/tinyusb/src/device/usbd.c:31:
[redacted]/pico-sdk/lib/tinyusb/src/osal/osal_pico.h: In function 'osal_semaphore_post':
[redacted]/pico-sdk/lib/tinyusb/src/osal/osal_pico.h:60:71: error: unused parameter 'in_isr' [-Werror=unused-parameter]
   60 | static inline bool osal_semaphore_post(osal_semaphore_t sem_hdl, bool in_isr)
      |                                                                       ^
In file included from [redacted]/pico-sdk/lib/tinyusb/src/osal/osal.h:57,
                 from [redacted]/pico-sdk/lib/tinyusb/src/tusb.h:38,
                 from [redacted]/pico-sdk/lib/tinyusb/src/device/usbd.c:31:
[redacted]/pico-sdk/lib/tinyusb/src/osal/osal_pico.h: In function 'osal_queue_send':
[redacted]/pico-sdk/lib/tinyusb/src/osal/osal_pico.h:162:79: error: unused parameter 'in_isr' [-Werror=unused-parameter]
  162 | static inline bool osal_queue_send(osal_queue_t qhdl, void const * data, bool in_isr)
      |
```